### ISSUE TITLE
Segmentation fault in __glDispatchCheckMultithreaded ()

### ISSUE THREAD

**Issue by neuromancer** [urxp/drally#5]
```
$ gdb --args drally_linux
...
Death Rally *** Full Version 1.1
Copyright (c) 1995, 1996 Remedy Entertainment, Ltd.
___60030h not implemented
GET_IRQ_ISR not implemented
SET_IRQ_ISR not implemented
GET_VRETRACE_INTERVAL not implemented
VRETRACE_WAIT_FOR_START not implemented
TIMER_SET_TIMER not implemented
ENABLE_IRQ not implemented
GET_IRQ_ISR not implemented
SET_IRQ_ISR not implemented
[dRally] Checking size of ENGINE.BPA
[dRally] Checking size of IBFILES.BPA
[dRally] Checking size of MENU.BPA
[dRally] Checking size of MUSICS.BPA
[dRally] Checking size of TR0.BPA
[dRally] Checking size of TR1.BPA
[dRally] Checking size of TR2.BPA
[dRally] Checking size of TR3.BPA
[dRally] Checking size of TR4.BPA
[dRally] Checking size of TR5.BPA
[dRally] Checking size of TR6.BPA
[dRally] Checking size of TR7.BPA
[dRally] Checking size of TR8.BPA
[dRally] Checking size of TR9.BPA
[dRally] Checking size of ./CINEM/SANIM.HAF
[dRally] Checking size of ./CINEM/SANIM.HAF
[dRally] Checking size of ./CINEM/ENDANI.HAF
[dRally] Checking size of ./CINEM/ENDANI0.HAF
[dRally] Checking size of dr.cfg

Loading music & effects, please wait...
[dRally] Checking size of ./CINEM/sanim.haf
[New Thread 0xf5253b40 (LWP 227301)]
[dRally.SOUND] Opening audio device.
[New Thread 0xd49ffb40 (LWP 227302)]
[dRally.SOUND] Audio opened: 22050 hz, 2 channels, 512 samples
[dRally.SOUND] MSX: tr0-mus.cmf, SFX: sanim-e.cmf
MEMORY_LOCK FAILED!
MEMORY_LOCK FAILED!
MEMORY_LOCK FAILED!
MEMORY_LOCK FAILED!
MEMORY_LOCK FAILED!
MEMORY_LOCK FAILED!
MEMORY_LOCK FAILED!
VGA13_SETMODE not implemented

Thread 1 "drally_linux" received signal SIGSEGV, Segmentation fault.
0xf715a45b in __glDispatchCheckMultithreaded () from /usr/lib32/libGLdispatch.so.0
(gdb) bt
#0  0xf715a45b in __glDispatchCheckMultithreaded () from /usr/lib32/libGLdispatch.so.0
#1  0xf71314ff in glXGetProcAddressARB () from /usr/lib32/libGLX.so.0
#2  0xf7ef7c7d in ?? () from /usr/lib32/libSDL2-2.0.so.0
#3  0xf7ebcb80 in ?? () from /usr/lib32/libSDL2-2.0.so.0
#4  0xf7ebcf3f in ?? () from /usr/lib32/libSDL2-2.0.so.0
#5  0xf7e58d98 in ?? () from /usr/lib32/libSDL2-2.0.so.0
#6  0xf7e5345b in ?? () from /usr/lib32/libSDL2-2.0.so.0
#7  0x5657abc1 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by urxp** [comment]
hi, thanks for your feedback, right now i have no idea what may cause this segfault, i have not encountered MEMORY_LOCK FAILED! error so far, my guess is something wrong with calling convention which causes me the most troubles

did you compile the binary or run the compiled one?

**Comment by neuromancer** [comment]
I compiled my own binary (I'm using clang 9 in ArchLinux).

**Comment by urxp** [comment]
have you had similar experience running other 32bit SDL2 based applications ?

**Comment by neuromancer** [comment]
I have a lot of games, but no crashes like this one. However, I'm using Steam for most of them, so perhaps it includes a better libGLdispatch.so? Do you have a simple code or game using SDL2 to compile using 32bit to test it?

**Comment by urxp** [comment]
i cannot think of any example right now, but i guess it's the "bitness" thing, do you have lib32-libglvnd installed? unfortunately i don't have any 64bit machine to test these things :(

**Comment by neuromancer** [comment]
Yes:
```
multilib/lib32-libglvnd 1.3.0-1 [installed]
    The GL Vendor-Neutral Dispatch library
```

Don't worry about this issue. Just continue with your (awesome!) work, I will keep testing and get back to you with the results here.

**Comment by neuromancer** [comment]
Latest git revision fails here:

```
Death Rally *** Full Version 1.1
Copyright (c) 1995, 1996 Remedy Entertainment, Ltd.
GET_VRETRACE_INTERVAL not implemented
VRETRACE_WAIT_FOR_START not implemented
TIMER_SET_TIMER not implemented
[dRally.File] Checking size of ENGINE.BPA
[dRally.File] Checking size of IBFILES.BPA
[dRally.File] Checking size of MENU.BPA
[dRally.File] Checking size of MUSICS.BPA
[dRally.File] Checking size of TR0.BPA
[dRally.File] Checking size of TR1.BPA
[dRally.File] Checking size of TR2.BPA
[dRally.File] Checking size of TR3.BPA
[dRally.File] Checking size of TR4.BPA
[dRally.File] Checking size of TR5.BPA
[dRally.File] Checking size of TR6.BPA
[dRally.File] Checking size of TR7.BPA
[dRally.File] Checking size of TR8.BPA
[dRally.File] Checking size of TR9.BPA
[dRally.File] Checking size of ./CINEM/SANIM.HAF
[dRally.File] Checking size of ./CINEM/SANIM.HAF
[dRally.File] Checking size of ./CINEM/ENDANI.HAF
[dRally.File] Checking size of ./CINEM/ENDANI0.HAF
[dRally.File] Checking size of dr.cfg

Program received signal SIGSEGV, Segmentation fault.
0x565824db in ?? ()
(gdb) bt
#0  0x565824db in ?? ()
#1  0xf7ffd900 in audit_list_string ()
#2  0xf7fe87b0 in ?? () from /lib/ld-linux.so.2
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) info registers 
eax            0xdc                220
ecx            0x5690bca0          1452326048
edx            0x8940              35136
ebx            0xb70               2928
esp            0xffffd68c          0xffffd68c
ebp            0x565cb000          0x565cb000
esi            0x569061b0          1452302768
edi            0xb76               2934
eip            0x565824db          0x565824db
eflags         0x10202             [ IF RF ]
cs             0x23                35
ss             0x2b                43
ds             0x2b                43
es             0x2b                43
fs             0x0                 0
gs             0x63                99
(gdb) x/i $eip
=> 0x565824db:	movaps %xmm3,0x20(%esp)
```

**Comment by urxp** [comment]
switched to software rendering and added -march=i386, hope it is a quick fix for now,  i need to  check it later, it has been coded quickly just to see some output

**Comment by neuromancer** [comment]
Recompiled with latest revision (089a10ec4fc2b953d4745cb4a467ba637aef5c2b). The intro video loaded (with music!) but it crashed in the main menu:

```
Thread 1 "drally_linux" received signal SIGSEGV, Segmentation fault.
0xf714545b in __glDispatchCheckMultithreaded ()
   from /usr/lib32/libGLdispatch.so.0
(gdb) bt
#0  0xf714545b in __glDispatchCheckMultithreaded ()
   from /usr/lib32/libGLdispatch.so.0
#1  0xf711d42f in ?? () from /usr/lib32/libGLX.so.0
#2  0xf711d68d in glXSwapBuffers () from /usr/lib32/libGLX.so.0
#3  0xf7e236a5 in ?? () from /usr/lib32/libSDL2-2.0.so.0
#4  0xf7de726e in ?? () from /usr/lib32/libSDL2-2.0.so.0
#5  0x5656ce47 in __PRESENTSCREEN__ () at drally_linux_c.c:309
#6  0x5656c685 in __GET_FRAME_COUNTER () at drally_linux_c.c:93
#7  0x56579523 in ___58c60h () at ___58c60h.c:11
#8  0x565af738 in ___2ab74h ()
#9  0x00000000 in ?? ()
(gdb) x/i $eip
=> 0xf714545b <__glDispatchCheckMultithreaded+155>:	movdqa 0xc(%esp),%xmm0
(gdb) info registers 
eax            0xf7b22700          -139319552
ecx            0x0                 0
edx            0x1                 1
ebx            0xf71a4f78          -149270664
esp            0xffffd120          0xffffd120
ebp            0xf71a5090          0xf71a5090
esi            0xb                 11
edi            0x56718080          1450279040
eip            0xf714545b          0xf714545b <__glDispatchCheckMultithreaded+155>
eflags         0x210296            [ PF AF SF IF RF ID ]
cs             0x23                35
ss             0x2b                43
ds             0x2b                43
es             0x2b                43
fs             0x0                 0
gs             0x63                99
```

**Comment by neuromancer** [comment]
Recompiled with latest revision (ecf85bf178edcd18e322dbdaa4af30a1a8b85d2c). It has the same crash, but only after you select some options in the main menu (e.g. Start Racing). Great work!

**Comment by urxp** [comment]
could you give me the backtrace please?

**Comment by neuromancer** [comment]
Sure:

```
Death Rally *** Full Version 1.1
[New Thread 0xf4d0db40 (LWP 9150)]
[dRally.SOUND] Opening audio device.
[New Thread 0xd47ffb40 (LWP 9151)]
[dRally.SOUND] Audio opened: 22050 hz, 2 channels, 512 samples

Loading music & effects, please wait...
[dRally.SOUND] MSX: tr0-mus.cmf, SFX: sanim-e.cmf
[dRally.Memory] Memory lock failed!
============= S3M resize: 443884 >>>>  14304
=============  XM resize: 628468 >>>>   1168
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.CINEM] Frames: 1626, Length: 5732 [81.89s]
[dRally.SOUND] MSX: MEN-MUS.CMF, SFX: MEN-SAM.CMF
[dRally.Memory] Memory lock failed!
============= S3M resize: 505857 >>>>  53840
=============  XM resize: 323793 >>>>    639
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!

Thread 1 "drally_linux" received signal SIGSEGV, Segmentation fault.
0xf714545b in __glDispatchCheckMultithreaded () from /usr/lib32/libGLdispatch.so.0
(gdb) bt
#0  0xf714545b in __glDispatchCheckMultithreaded () from /usr/lib32/libGLdispatch.so.0
#1  0xf711d42f in ?? () from /usr/lib32/libGLX.so.0
#2  0xf711d68d in glXSwapBuffers () from /usr/lib32/libGLX.so.0
#3  0xf7e236a5 in ?? () from /usr/lib32/libSDL2-2.0.so.0
#4  0xf7de726e in ?? () from /usr/lib32/libSDL2-2.0.so.0
#5  0x56569d60 in __PRESENTSCREEN__ () at drally_linux_c.c:271
#6  0x56569765 in __GET_FRAME_COUNTER () at drally_linux_c.c:83
#7  0x56574bf0 in ___58c60h () at ___58c60h.c:10
#8  0x565ce8b6 in ___3d536h ()
#9  0x00640000 in ?? ()
#10 0x5665d400 in VESA101_ACTIVESCREEN ()
#11 0x00000000 in ?? ()
```

**Comment by neuromancer** [comment]
Yahooooo!, no crashes in the latest release (bddd8c4798be28ede143b9203a6e73740f19c944). The game is playable (at least, races are staring and you can drive). When is the first alpha release coming? :smile:

**Comment by urxp** [comment]
That's great, thanks. There won't be any release until the last line of assembly disappears.
